tap "dart-lang/dart"
tap "epk/epk"
tap "homebrew/bundle"
tap "homebrew/services"
tap "nikitabobko/tap"
tap "oven-sh/bun"
tap "porter-dev/porter"
tap "sass/sass"
brew "little-cms2"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "cryptography"
brew "python@3.12"
brew "awscli"
brew "azure-cli"
brew "bat"
brew "glib"
brew "chezmoi"
brew "lima"
brew "colima"
brew "docker"
brew "docker-machine"
brew "eza"
brew "fastfetch"
brew "fd"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "openjpeg"
brew "leptonica"
brew "tesseract"
brew "ffmpeg"
brew "flyctl"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git-delta"
brew "gnupg"
brew "gpgme"
brew "shared-mime-info"
brew "imagemagick"
brew "imagemagick@6"
brew "jq"
brew "lazygit"
brew "mas"
brew "neovim"
brew "openjdk"
brew "openssl@1.1"
brew "pnpm"
brew "poppler"
brew "postgresql@17"
brew "pyenv"
brew "python@3.11"
brew "qemu"
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "rust"
brew "sevenzip"
brew "sops"
brew "starship"
brew "tailscale"
brew "tmux"
brew "woff2"
brew "yarn"
brew "yazi"
brew "zellij"
brew "zoxide"
brew "oven-sh/bun/bun"
brew "porter-dev/porter/porter"
brew "sass/sass/migrator"
cask "1password"
cask "1password-cli"
cask "aerospace"
cask "alfred"
cask "arc"
cask "bbedit"
cask "bitwarden"
cask "blender"
cask "boop"
cask "brave-browser"
cask "caffeine"
cask "calibre"
cask "discord"
cask "doppler-app"
cask "dropbox"
cask "fantastical"
cask "figma"
cask "firefox"
cask "font-sf-mono-nerd-font"
cask "font-symbols-only-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "google-chrome@canary"
cask "graphiql"
cask "hazel"
cask "httpie-desktop"
cask "hyperkey"
cask "imageoptim"
cask "iterm2"
cask "itsycal"
cask "jordanbaird-ice"
cask "leader-key"
cask "microsoft-edge"
cask "mimestream"
cask "netnewswire"
cask "ngrok"
cask "notion"
cask "notion-calendar"
cask "obsidian"
cask "ogdesign-eagle"
cask "openemu"
cask "oracle-jdk"
cask "orbstack"
cask "orion"
cask "postico"
cask "raspberry-pi-imager"
cask "raycast"
cask "rectangle"
cask "retrobatch"
cask "rocket"
cask "setapp"
cask "signal"
cask "slack"
cask "spline"
cask "sublime-text"
cask "superduper"
cask "transmission"
cask "tuple"
cask "visual-studio-code"
cask "vivaldi"
cask "vlc"
cask "whatsapp"
cask "zen"
cask "zoom"
vscode "aaron-bond.better-comments"
vscode "akamud.vscode-theme-onedark"
vscode "astro-build.astro-vscode"
vscode "bierner.github-markdown-preview"
vscode "bierner.markdown-checkbox"
vscode "bierner.markdown-emoji"
vscode "bierner.markdown-footnotes"
vscode "bierner.markdown-mermaid"
vscode "bierner.markdown-preview-github-styles"
vscode "bierner.markdown-yaml-preamble"
vscode "biomejs.biome"
vscode "bradgashler.htmltagwrap"
vscode "bradlc.vscode-tailwindcss"
vscode "capaj.vscode-standardjs-snippets"
vscode "catppuccin.catppuccin-vsc"
vscode "chakrounanas.turbo-console-log"
vscode "davidbwaters.macos-modern-theme"
vscode "dbaeumer.vscode-eslint"
vscode "dotjoshjohnson.xml"
vscode "editorconfig.editorconfig"
vscode "enkia.tokyo-night"
vscode "esbenp.prettier-vscode"
vscode "file-icons.file-icons"
vscode "fooo.ruby-spec-runner"
vscode "ginfuru.better-nunjucks"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.remotehub"
vscode "github.vscode-pull-request-github"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-execution"
vscode "graphql.vscode-graphql-syntax"
vscode "gruntfuggly.todo-tree"
vscode "hbenl.vscode-test-explorer"
vscode "jkjustjoshing.vscode-text-pastry"
vscode "kaiwood.endwise"
vscode "letrieu.expand-region"
vscode "lokalise.i18n-ally"
vscode "loriscro.super"
vscode "marcoroth.stimulus-lsp"
vscode "mjmlio.vscode-mjml"
vscode "ms-azure-load-testing.microsoft-testing"
vscode "ms-azuretools.azure-dev"
vscode "ms-azuretools.vscode-azure-github-copilot"
vscode "ms-azuretools.vscode-azure-mcp-server"
vscode "ms-azuretools.vscode-azureappservice"
vscode "ms-azuretools.vscode-azurecontainerapps"
vscode "ms-azuretools.vscode-azurefunctions"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-azurestaticwebapps"
vscode "ms-azuretools.vscode-azurestorage"
vscode "ms-azuretools.vscode-azurevirtualmachines"
vscode "ms-azuretools.vscode-cosmosdb"
vscode "ms-vscode.azure-repos"
vscode "ms-vscode.remote-repositories"
vscode "ms-vscode.sublime-keybindings"
vscode "ms-vscode.test-adapter-converter"
vscode "ms-vscode.vscode-node-azure-pack"
vscode "ms-vscode.wasm-wasi-core"
vscode "ms-windows-ai-studio.windows-ai-studio"
vscode "openai.openai-chatgpt-adhoc"
vscode "sdras.vue-vscode-snippets"
vscode "shanehofstetter.rails-i18n"
vscode "shopify.ruby-lsp"
vscode "sissel.shopify-liquid"
vscode "sleistner.vscode-fileutils"
vscode "stylelint.vscode-stylelint"
vscode "svelte.svelte-vscode"
vscode "tamasfe.even-better-toml"
vscode "teabyii.ayu"
vscode "teamsdevapp.vscode-ai-foundry"
vscode "unifiedjs.vscode-mdx"
vscode "usernamehw.errorlens"
vscode "vitest.explorer"
vscode "vue.volar"
vscode "vunguyentuan.vscode-postcss"
vscode "wmaurer.change-case"
vscode "yoavbls.pretty-ts-errors"
mas 'Things', id: 4280696
mas 'Hand Mirror', id: 1502839586
mas 'RocketSim', id: 1504940162
mas 'Developer', id: 640199958
mas 'GoodLinks', id: 1474335294
mas 'Keynote', id: 409183694
mas 'Tripsy', id: 1429967544
mas 'Color Picker', id: 1545870783
mas 'Simple Comic', id: 1497435571
mas 'LimeChat', id: 414030210
mas 'Windows App', id: 1295203466
mas 'GarageBand', id: 682658836
mas 'Play Legacy', id: 6444542118
mas 'Playgrounds', id: 1496833156
mas 'Amphetamine', id: 937984704
mas 'stts', id: 1187772509
mas 'rcmd', id: 1596283165
mas 'Reeder', id: 6475002485
mas 'Xcode', id: 497799835
mas 'Pastel', id: 413897608
mas 'Numbers', id: 409203825
mas 'Croissant', id: 6670288979
mas 'Quests', id: 1447415753
mas 'iMovie', id: 408981434
mas 'Dropover', id: 1355679052
mas 'Pages', id: 409201541
mas 'Broadcasts', id: 1469995354
mas 'Velja', id: 1607635845
mas 'Photomator', id: 1444636541
mas 'AnyExif', id: 1621435983
